name: "test"
on: push
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Go app directory
        env:
          EC2_SSH:  ${{ secrets.AWS_EC2_SSH_KEY}} 
        run: |
            cd my-blog
            ls
            echo "Using AWS EC2 Secret ${{ secrets.AWS_EC2_SSH_KEY }}"