name: "test"
on: push
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    environment: test_env
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Go app directory
        run:  cd my-blog
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.AWS_EC2_SSH_KEY }}
            REMOTE_HOST: 3.72.87.209
            REMOTE_USER: ec2-user
            TARGET: app